// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthReq struct {
	Authorization        string   `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetAuthorization() string {
	if m != nil {
		return m.Authorization
	}
	return ""
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

type AuthResp struct {
	Email     string               `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ExpiresAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// number of requests allowed until expire.
	// -1 means unlimited. 0 means disallow.
	Quota int32 `protobuf:"varint,4,opt,name=quota,proto3" json:"quota,omitempty"`
	// error description for user.
	ErrorDescription string `protobuf:"bytes,5,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	Token            *Token `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	// group that email belongs to.
	GroupId              string   `protobuf:"bytes,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthResp) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *AuthResp) GetQuota() int32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *AuthResp) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

func (m *AuthResp) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthResp) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthReq)(nil), "auth.AuthReq")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*AuthResp)(nil), "auth.AuthResp")
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2) }

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xc9, 0xff, 0xdf, 0x34, 0xe9, 0x54, 0xb1, 0x2e, 0x1e, 0x62, 0x41, 0x4c, 0x83, 0x87,
	0x80, 0x90, 0x80, 0x9e, 0x3c, 0x16, 0xbc, 0xd4, 0x63, 0xc8, 0x3d, 0x6c, 0x93, 0x31, 0x5d, 0x6c,
	0xba, 0xdb, 0xdd, 0x0d, 0x58, 0x3f, 0xae, 0x9f, 0x44, 0x32, 0x9b, 0x22, 0x5e, 0x42, 0xde, 0x9b,
	0xb7, 0xf3, 0xf6, 0xb7, 0x70, 0xc5, 0x7b, 0xbb, 0xcb, 0x87, 0x4f, 0xa6, 0xb4, 0xb4, 0x92, 0x4d,
	0x86, 0xff, 0xe5, 0x7d, 0x2b, 0x65, 0xbb, 0xc7, 0x9c, 0xbc, 0x6d, 0xff, 0x9e, 0x5b, 0xd1, 0xa1,
	0xb1, 0xbc, 0x53, 0x2e, 0x96, 0xe4, 0x10, 0xac, 0x7b, 0xbb, 0x2b, 0xf0, 0xc8, 0x1e, 0xe0, 0x72,
	0x38, 0x23, 0xb5, 0xf8, 0xe2, 0x56, 0xc8, 0x43, 0xe4, 0xc5, 0x5e, 0x3a, 0x2b, 0xfe, 0x9a, 0xc9,
	0x06, 0xfc, 0x52, 0x7e, 0xe0, 0x81, 0xad, 0xe0, 0x82, 0xd7, 0x35, 0x1a, 0x53, 0xd9, 0x41, 0x8f,
	0xe9, 0xb9, 0xf3, 0x5c, 0xe4, 0x0e, 0x80, 0x66, 0x95, 0x3d, 0x29, 0x8c, 0xfe, 0x51, 0x60, 0x46,
	0x4e, 0x79, 0x52, 0x98, 0x7c, 0x7b, 0x10, 0xba, 0x72, 0xa3, 0xd8, 0x0d, 0xf8, 0xd8, 0x71, 0xb1,
	0x1f, 0xf7, 0x38, 0xc1, 0x5e, 0x00, 0xf0, 0x53, 0x09, 0x8d, 0xa6, 0xe2, 0x36, 0xfa, 0x1f, 0x7b,
	0xe9, 0xfc, 0x69, 0x99, 0x39, 0xa8, 0xec, 0x0c, 0x95, 0x95, 0x67, 0xa8, 0x62, 0x36, 0xa6, 0xd7,
	0x76, 0x58, 0x78, 0xec, 0xa5, 0xe5, 0xd1, 0x24, 0xf6, 0x52, 0xbf, 0x70, 0x82, 0x3d, 0xc2, 0x35,
	0x6a, 0x2d, 0x75, 0xd5, 0xa0, 0xa9, 0xb5, 0x50, 0x04, 0xea, 0x53, 0xe5, 0x82, 0x06, 0xaf, 0xbf,
	0x3e, 0x5b, 0x81, 0xef, 0xd8, 0x02, 0x2a, 0x9e, 0x67, 0xf4, 0xbe, 0xc4, 0x56, 0xb8, 0x09, 0xbb,
	0x85, 0xb0, 0xd5, 0xb2, 0x57, 0x95, 0x68, 0xa2, 0x90, 0xd6, 0x04, 0xa4, 0x37, 0xcd, 0xdb, 0x24,
	0x9c, 0x2e, 0x82, 0xed, 0x94, 0x6e, 0xf9, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x5a, 0xb6,
	0x8a, 0xa1, 0x01, 0x00, 0x00,
}
