// Code generated by protoc-gen-go. DO NOT EDIT.
// source: settings/settings.proto

package settings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Settings struct {
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EndpointUrl string `protobuf:"bytes,1,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	Certificate string `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// requires oauth2 for cloud service.
	Oauth2Cloud          bool     `protobuf:"varint,4,opt,name=oauth2_cloud,json=oauth2Cloud,proto3" json:"oauth2_cloud,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Settings) Reset()         { *m = Settings{} }
func (m *Settings) String() string { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()    {}
func (*Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bfd59e429426d0, []int{0}
}

func (m *Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settings.Unmarshal(m, b)
}
func (m *Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settings.Marshal(b, m, deterministic)
}
func (m *Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settings.Merge(m, src)
}
func (m *Settings) XXX_Size() int {
	return xxx_messageInfo_Settings.Size(m)
}
func (m *Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_Settings proto.InternalMessageInfo

func (m *Settings) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Settings) GetEndpointUrl() string {
	if m != nil {
		return m.EndpointUrl
	}
	return ""
}

func (m *Settings) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *Settings) GetOauth2Cloud() bool {
	if m != nil {
		return m.Oauth2Cloud
	}
	return false
}

type SettingsReq struct {
	UseCase              string   `protobuf:"bytes,2,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingsReq) Reset()         { *m = SettingsReq{} }
func (m *SettingsReq) String() string { return proto.CompactTextString(m) }
func (*SettingsReq) ProtoMessage()    {}
func (*SettingsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bfd59e429426d0, []int{1}
}

func (m *SettingsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsReq.Unmarshal(m, b)
}
func (m *SettingsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsReq.Marshal(b, m, deterministic)
}
func (m *SettingsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsReq.Merge(m, src)
}
func (m *SettingsReq) XXX_Size() int {
	return xxx_messageInfo_SettingsReq.Size(m)
}
func (m *SettingsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsReq.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsReq proto.InternalMessageInfo

func (m *SettingsReq) GetUseCase() string {
	if m != nil {
		return m.UseCase
	}
	return ""
}

type SettingsResp struct {
	Settings             *Settings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SettingsResp) Reset()         { *m = SettingsResp{} }
func (m *SettingsResp) String() string { return proto.CompactTextString(m) }
func (*SettingsResp) ProtoMessage()    {}
func (*SettingsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bfd59e429426d0, []int{2}
}

func (m *SettingsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsResp.Unmarshal(m, b)
}
func (m *SettingsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsResp.Marshal(b, m, deterministic)
}
func (m *SettingsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsResp.Merge(m, src)
}
func (m *SettingsResp) XXX_Size() int {
	return xxx_messageInfo_SettingsResp.Size(m)
}
func (m *SettingsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsResp.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsResp proto.InternalMessageInfo

func (m *SettingsResp) GetSettings() *Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func init() {
	proto.RegisterType((*Settings)(nil), "settings.Settings")
	proto.RegisterType((*SettingsReq)(nil), "settings.SettingsReq")
	proto.RegisterType((*SettingsResp)(nil), "settings.SettingsResp")
}

func init() {
	proto.RegisterFile("settings/settings.proto", fileDescriptor_a4bfd59e429426d0)
}

var fileDescriptor_a4bfd59e429426d0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3d, 0x4f, 0x04, 0x21,
	0x10, 0x86, 0xc3, 0xb9, 0x51, 0x1c, 0xae, 0x30, 0xd3, 0x88, 0xdd, 0xba, 0xd5, 0x55, 0x98, 0x9c,
	0xbd, 0xcd, 0x75, 0x96, 0x6b, 0xac, 0x37, 0xc8, 0x8d, 0x4a, 0xb2, 0xc2, 0xca, 0xc7, 0x5f, 0xf0,
	0x77, 0x9b, 0x63, 0x05, 0xaf, 0x9b, 0x79, 0x78, 0x32, 0x79, 0x5f, 0xe0, 0x36, 0x52, 0x4a, 0xd6,
	0x7d, 0xc4, 0x87, 0x3a, 0xa8, 0x25, 0xf8, 0xe4, 0x91, 0xd7, 0x7d, 0xf8, 0x61, 0xc0, 0x5f, 0xfe,
	0x16, 0x44, 0xe8, 0x9c, 0xfe, 0x22, 0x79, 0xd1, 0xb3, 0xdd, 0xf5, 0x58, 0x66, 0xbc, 0x87, 0x2d,
	0xb9, 0xe3, 0xe2, 0xad, 0x4b, 0x53, 0x0e, 0xb3, 0x64, 0xe5, 0x4d, 0x54, 0xf6, 0x1a, 0x66, 0xec,
	0x41, 0x18, 0x0a, 0xc9, 0xbe, 0x5b, 0xa3, 0x13, 0xc9, 0xcd, 0x6a, 0x9c, 0xa1, 0xd3, 0x11, 0xaf,
	0x73, 0xfa, 0xdc, 0x4f, 0x66, 0xf6, 0xf9, 0x28, 0xbb, 0x9e, 0xed, 0xf8, 0x28, 0x56, 0x76, 0x38,
	0xa1, 0x41, 0x81, 0xa8, 0x39, 0x46, 0xfa, 0xc6, 0x3b, 0xe0, 0x39, 0xd2, 0x64, 0x74, 0xac, 0x07,
	0xaf, 0x72, 0xa4, 0x83, 0x8e, 0xf4, 0xdc, 0x71, 0x76, 0xb3, 0x19, 0x9e, 0x60, 0xfb, 0xef, 0xc7,
	0x05, 0x15, 0xb4, 0x52, 0x25, 0xa3, 0xd8, 0xa3, 0x6a, 0xad, 0x9b, 0xd9, 0x9c, 0xb7, 0xcb, 0xf2,
	0x13, 0x8f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x52, 0xd2, 0x36, 0x24, 0x01, 0x00, 0x00,
}
